### PR TITLE
Good fix

### LINKED ISSUE #27: Cannot send on macos
Hello,

Using a locally built version of bob (using opam pin) on a macos 12.6.1 (x86-64), the send does not work see below:

```
> bob send <file> -r <our relay> -vv
Password: wheayantelt-moadth
[ 62196][     DEBUG][            bob.pack]: Compute <file>.
[ 62196][     DEBUG][          bob.stream]: End of the file: <file>
[ 62196][     DEBUG][           bob.fiber]: Close the file-description 4
[ 62196][     DEBUG][            bob.pack]: <file> -> 299192bd26006baa2b1704c6924368a21600dbff
[ 62196][     DEBUG][            bob.pack]: Store of <file>.
[ 62196][     DEBUG][            bob.pack]: The PACK stream is ready to be sent.
[ 62196][     DEBUG][           bob.fiber]: Call to connect() (operating system: Unix)
[ 62196][     DEBUG][           bob.fiber]: Set file-descriptor into a non-blocking mode.
[ 62196][     DEBUG][           bob.fiber]: Try to connect to <our relay>
[ 62196][     ERROR][           bob.fiber]: Got an error for a non-blocking connect(): Operation now in progress.
bob: connect(): Operation now in progress.

[ 62196][     DEBUG][           bob.fiber]: Close remaining file-descriptions:
[]
```

Any hint would be appreciated.

### PR DESCRIPTION
**Pull request by dinosaure**
This series of commit fixes #27. I did not test it yet on MacOS but it's working on FreeBSD. Thanks to @reynir, @rand and @hannesm who help me to find the bug and their patiences. Thanks to @kit-ty-kate for her machine and, of course, @fdagnat who spotted the bug initially and his patience for debugging.

The real bug is fixed by the commit: 01c3176c8420f360e26461aff00d2713f18f48fa.

I will upgrade the unikernel as soon as I can and merge this PR then. Currently, we changed a bit the transmission protocol: we added a `CLOSE_NOTIFY` (as TLS or `QUIT` for SMTP) to be able to keep alive the connection as long the transfer is not totally done.

### CODE REVIEW

File: lib/bob_dns.ml [hunk 1]
```diff
@@ -63,7 +63,12 @@ module Transport :
                      (msgf "Error %s connecting to nameserver %a:%d"
                         (Unix.error_message errno) Ipaddr.pp ip port))
             | Ok _ as v -> Fiber.return v)
-          (fun () -> Fiber.wait cancel >>| fun () -> Error (msgf "Cancelled"))
+          (fun () ->
+            Fiber.wait cancel >>| fun () ->
+            Log.warn (fun m ->
```
Comment (reynir) [inline lib/bob_dns.ml:68]: It was at line 101 (106) I meant it would be nice to have a warning. Where we are asked to cancel something which we can't cancel.
